name: API Test Suite (Allure + Maven)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Print java & maven versions
        run: |
          java -version
          mvn -v

      - name: Run Maven tests (generate Allure results)
        run: mvn -B -U clean test -DsuiteXmlFile=testng.xml -Denv=prod

      - name: Show generated target files (debug)
        run: |
          echo "=== target listing ==="
          ls -la target || true
          echo "=== target/allure-results listing ==="
          ls -la target/allure-results || true
          echo "=== find result jsons under target ==="
          find target -type f -name "*-result.json" -o -name "*-container.json" -o -name "*-attachment.txt" -print || true

      - name: Upload raw Allure results (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Install Allure CLI
        if: ${{ always() }}
        run: |
          set -e
          ALLURE_VER=2.29.0
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VER}/allure-${ALLURE_VER}.tgz -O /tmp/allure.tgz
          sudo tar -zxvf /tmp/allure.tgz -C /opt/
          sudo ln -sf /opt/allure-${ALLURE_VER}/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure HTML report (if results exist)
        if: ${{ always() }}
        run: |
          set -e
          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
            allure generate target/allure-results -o target/allure-report --clean
            echo "Allure HTML generated at target/allure-report"
            ls -la target/allure-report || true
          else
            echo "No allure-results found; skipping HTML generation"
          fi

      - name: Upload Allure HTML report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
