name: API Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Print java & maven versions
        run: |
          java -version
          mvn -v

      - name: Run Maven tests (generate Allure results)
        run: mvn -B -U clean test -DsuiteXmlFile=./testng.xml -Denv=prod

      - name: "Debug: check surefire and allure"
        run: |
          echo "=== surefire reports ==="
          ls -R target/surefire-reports || true
          echo "=== allure results ==="
          ls -R target/allure-results || true

      - name: Show generated target files (debug)
        run: |
          echo "=== target listing ==="
          ls -la target || true
          echo "=== target/allure-results listing ==="
          ls -la target/allure-results || true
          echo "=== find result jsons under target ==="
          find target -type f -name "*-result.json" -o -name "*-container.json" -o -name "*-attachment.txt" -print || true
          echo "=== tail testng-results.xml (if present) ==="
          [ -f target/surefire-reports/testng-results.xml ] && tail -n 200 target/surefire-reports/testng-results.xml || echo "no testng-results.xml"

      - name: Upload raw Allure results (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip curl
          curl -sSL https://repo.maven.apache.org/maven2/io/qameta/allure/allure/2.19.0/allure-2.19.0.zip -o /tmp/allure.zip
          mkdir -p $HOME/.allure && unzip -q /tmp/allure.zip -d $HOME/.allure
          echo "$HOME/.allure/allure-2.19.0/bin" >> $GITHUB_PATH

      - name: Generate Allure HTML report (if results present)
        if: ${{ always() }}
        run: |
          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
            allure generate target/allure-results -o target/allure-report --clean
            ls -la target/allure-report || true
          else
            echo "No allure-results found; skipping report generation"
          fi

      - name: Upload Allure HTML report (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
